function test_suite=test_specoptset()
  initTestSuite;
end
function test_specoptset_()
   true_opt = struct('dflag','mean','ftype', 'w',... 
         'thtype','r','noverlap', 0,'window', [], 'message', 2000,... 
         'plotflag', 'off','delay', 0,'nharm', 2,'gravity', 9.80629386676700,... 
         'wdensity', 1027.78633943154,'bet', 1,'igam', 1,'x_axisdir', 90,... 
         'y_axisdir', 0, 'maxiter', 25, 'coefabstol',  0.01,... 
         'errortol',  0.01,'minmodelorder',  1,'maxmodelorder', [],... 
         'relax',  1, 'maxcoef', []); 
  assert(specoptset('dat2dspec'), true_opt, 1e-10); 
  true_opt.ftype='f'; 
  true_opt.thtype='degrees'; 
  assert(specoptset('dat2dspec','ftype','f','thtype','degrees'), ... 
         true_opt, 1e-10);
end
